# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftViewCodeSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftViewCodeSample
  pod 'SnapKit', '~> 5.0.0'
  pod 'Quick'
  pod 'Nimble'
  pod 'Nimble-Snapshots'

  target 'SwiftViewCodeSampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
  end

  target 'SwiftViewCodeSampleUITests' do
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
  end

end
